### ISSUE TITLE
Android 14 - startForeground() error

### ISSUE THREAD

**Issue by lmarcelocc** [brunochikuji/cordova-plugin-background-mode#5]
Hello @brunochikuji ,

I'm having an issue testing on Android 14. It happens only when user did not granted permissions and `cordova-plugin-background-mode` calls `keepAwake() -> startForeground()`.

I'm trying to find a solution. My first though was to subscribe to those permissions and only call `keepAwake()` when granted.
My knowledge here is limited, but will keep this post update with my findings.

```java
FATAL EXCEPTION: main
Process: io.gaf.map, PID: 17439
java.lang.RuntimeException: Unable to create service de.appplant.cordova.plugin.background.ForegroundService: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{e8f9104 17439:io.gaf.map/u0a389} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:230)
at android.os.Looper.loop(Looper.java:319)
at android.app.ActivityThread.main(ActivityThread.java:8919)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
Caused by: java.lang.SecurityException: Starting FGS with type location callerApp=ProcessRecord{e8f9104 17439:io.gaf.map/u0a389} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_LOCATION] any of the permissions allOf=false [android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION]  and the app must be in the eligible state/exemptions to access the foreground only permission
at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
at android.os.Parcel.createException(Parcel.java:3053)
at android.os.Parcel.readException(Parcel.java:3036)
at android.os.Parcel.readException(Parcel.java:2978)
at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7234)
at android.app.Service.startForeground(Service.java:862)
at de.appplant.cordova.plugin.background.ForegroundService.keepAwake(ForegroundService.java:134)
at de.appplant.cordova.plugin.background.ForegroundService.onCreate(ForegroundService.java:101)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:230) 
at android.os.Looper.loop(Looper.java:319) 
at android.app.ActivityThread.main(ActivityThread.java:8919) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) `

**Comment by julianCast** [comment]
Hi! When was this solved? what version? thanks

**Comment by lmarcelocc** [comment]
No clue if it was fixed meanwhile. I've fixed it when I add this issue here with a patch. No clue if it is still working :)
